export const ASSIGN_ROLES_ACTION_TYPES = {
    FETCH_ASSIGN_ROLES_START: 'assign-roles/FETCH_ASSIGN_ROLES_START',
    FETCH_ASSIGN_ROLES_SUCCESS: 'assign-roles/FETCH_ASSIGN_ROLES_SUCCESS',
    FECH_ASSIGN_ROLES_FAILED: 'assign-roles/FECH_ASSIGN_ROLES_FAILED',
    UPDATE_ROLES: 'assign-roles/UPDATE_ROLES',
    UPDATE_ROLES_SUCCESS:'assign-roles/UPDATE_ROLES_SUCCESS',
    UPDATE_ROLES_ERROR:'assign-roles/UPDATE_ROLES_ERROR',
    HIDE_ALERT:'assign-roles/HIDE_ALERT'
}