export const LOGIN_ACTION_TYPES = {
    LOGIN_IN_START: 'login/LOGIN_IN_START',
    LOGIN_IN_SUBMIT_OTP: 'login/LOGIN_IN_SUBMIT_OTP',
    LOGIN_IN_SUCCESS: 'login/LOGIN_IN_SUCCESS',
    LOGIN_IN_FAILED: 'login/LOGIN_IN_FAILED',
    LOGOUT_START:'login/LOGOUT_START'
}