export const HOLIDAYS_ACTION_TYPES = {
    FETCH_HOLIDAYS_START: 'holiday/FETCH_HOLIDAYS_START',
    FETCH_HOLIDAYS_SUCCESS: 'holiday/FETCH_HOLIDAYS_SUCCESS',
    FETCH_HOLIDAYS_FAILED: 'holiday/FETCH_HOLIDAYS_FAILED'
}