export const EMPLOYEES_ACTION_TYPES = {
    FETCH_EMPLOYEES_START: 'employees/FETCH_EMPLOYEES_START',
    FETCH_EMPLOYEES_SUCCESS: 'employees/FETCH_EMPLOYEES_SUCCESS',
    FETCH_EMPLOYEES_FAILED: 'employees/FETCH_EMPLOYEES_FAILED'
}