export const EMPLOYEES_ACTION_TYPES = {
    FETCH_EMPLOYEES_START: 'employees/FETCH_EMPLOYEES_START',
    FETCH_EMPLOYEES_SUCCESS: 'employees/FETCH_EMPLOYEES_SUCCESS',
    FETCH_EMPLOYEES_FAILED: 'employees/FETCH_EMPLOYEES_FAILED',
    FETCH_EMPLOYEE_START: 'employees/FETCH_EMPLOYEE_START',
    FETCH_EMPLOYEE_SUCCESS: 'employees/FETCH_EMPLOYEE_SUCCESS',
    FETCH_EMPLOYEE_FAILED: 'employees/FETCH_EMPLOYEE_FAILED'
}