export const JD_ACTION_TYPES = {
    FETCH_JD_START: 'jd/FETCH_JD_START',
    FETCH_JD_SUCCESS: 'jd/FETCH_JD_SUCCESS',
    FETCH_JD_FAILED: 'jd/FETCH_JD_FAILED',
    FETCH_JOB_RECORD_START:'jd/FETCH_JOB_RECORD_START',
    FETCH_JOB_RECORD_SUCCESS:'jd/FETCH_JOB_RECORD_SUCCESS',
    FETCH_JOB_RECORD_FAILED:'jd/FETCH_JOB_RECORD_FAILED'
}