export const MONTHLY_RATINGS_ACTION_TYPES = {
    FETCH_MONTHLY_RATINGS_START: 'monthly_ratings/FETCH_MONTHLY_RATINGS_START',
    FETCH_MONTHLY_RATINGS_SUCCESS: 'monthly_ratings/FETCH_MONTHLY_RATINGS_SUCCESS',
    FETCH_MONTHLY_RATINGS_FAILED: 'monthly_ratings/FETCH_MONTHLY_RATINGS_FAILED'
}